name: Build and Test

on:
  pull_request:
    branches: [ main, development, release ]

jobs:
  build:
    runs-on: ubuntu-18.16.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
